use anyhow::{Context, Result, bail};
use flate2::read::DeflateDecoder;
use sha1::{Digest, Sha1};
use std::io::Read;
use std::{fs, path::Path};

use super::cipher::decrypt_aes;

/// NG keys and decrypt tables, deflated and encrypted with the game's AES key.
/// Generated by CodeWalker, which ships the same blob for the same reason.
const EMBEDDED_MAGIC: &[u8] = include_bytes!("../../resources/magic.dat");

const NG_KEY_BYTES: usize = 101 * 272;
const NG_TABLE_BYTES: usize = 17 * 16 * 1024;

/// GTA V cryptographic keys needed for RPF decryption.
pub struct GtaKeys {
    pub aes_key: [u8; 32],
    pub ng_keys: Vec<Vec<u8>>,
    pub ng_decrypt_tables: Box<[[[u32; 256]; 16]; 17]>,
}

impl GtaKeys {
    /// Load pre-extracted keys from a directory.
    /// Expected files: gtav_aes_key.dat, gtav_ng_key.dat, gtav_ng_decrypt_tables.dat
    pub fn load_from_path(path: &Path) -> Result<Self> {
        let aes_bytes = fs::read(path.join("gtav_aes_key.dat"))
            .context("Missing gtav_aes_key.dat")?;
        if aes_bytes.len() != 32 {
            bail!("gtav_aes_key.dat has wrong size (expected 32 bytes)");
        }
        let aes_key: [u8; 32] = aes_bytes.try_into().unwrap();

        let ng_key_bytes = fs::read(path.join("gtav_ng_key.dat"))
            .context("Missing gtav_ng_key.dat")?;
        let ng_keys = read_ng_keys(&ng_key_bytes)?;

        let ng_table_bytes = fs::read(path.join("gtav_ng_decrypt_tables.dat"))
            .context("Missing gtav_ng_decrypt_tables.dat")?;
        let ng_decrypt_tables = read_ng_tables(&ng_table_bytes)?;

        Ok(Self { aes_key, ng_keys, ng_decrypt_tables })
    }

    /// Extract keys from a GTA5.exe and optionally save them to a directory.
    ///
    /// Only the AES key is still stored as plain bytes in the executable.
    /// Newer builds dropped the NG keys and decrypt tables, so those come from
    /// the bundled magic data, which that AES key unlocks.
    pub fn extract_from_exe(exe_path: &Path, save_to: Option<&Path>) -> Result<Self> {
        let exe_data = fs::read(exe_path).context("Failed to read GTA5.exe")?;

        let aes_bytes = search_hash(&exe_data, &PC_AES_KEY_HASH, 32)
            .context("AES key not found — is this a GTA V PC executable?")?;
        let aes_key: [u8; 32] = aes_bytes.try_into().unwrap();

        let magic = unwrap_magic(EMBEDDED_MAGIC, &aes_key)?;
        let ng_keys = read_ng_keys(&magic[..NG_KEY_BYTES])?;
        let ng_decrypt_tables = read_ng_tables(&magic[NG_KEY_BYTES..])?;

        let keys = Self { aes_key, ng_keys, ng_decrypt_tables };

        if let Some(out_path) = save_to {
            keys.save_to_path(out_path)?;
        }

        Ok(keys)
    }

    pub fn save_to_path(&self, path: &Path) -> Result<()> {
        fs::create_dir_all(path)?;
        fs::write(path.join("gtav_aes_key.dat"), &self.aes_key)?;
        fs::write(path.join("gtav_ng_key.dat"), write_ng_keys(&self.ng_keys))?;
        fs::write(path.join("gtav_ng_decrypt_tables.dat"), write_ng_tables(&self.ng_decrypt_tables))?;
        eprintln!("[Keys] Saved to {}", path.display());
        Ok(())
    }
}

fn read_ng_keys(data: &[u8]) -> Result<Vec<Vec<u8>>> {
    const KEY_SIZE: usize = 272;
    const KEY_COUNT: usize = 101;
    if data.len() < KEY_SIZE * KEY_COUNT {
        bail!("NG key data too small: {} bytes", data.len());
    }
    Ok((0..KEY_COUNT)
        .map(|i| data[i * KEY_SIZE..(i + 1) * KEY_SIZE].to_vec())
        .collect())
}

fn write_ng_keys(keys: &[Vec<u8>]) -> Vec<u8> {
    keys.iter().flat_map(|k| k.iter().cloned()).collect()
}

fn read_ng_tables(data: &[u8]) -> Result<Box<[[[u32; 256]; 16]; 17]>> {
    const EXPECTED: usize = 17 * 16 * 1024;
    if data.len() < EXPECTED {
        bail!("NG table data too small: {} bytes (expected {})", data.len(), EXPECTED);
    }
    let mut tables = vec![[[0u32; 256]; 16]; 17];
    let mut offset = 0;
    for i in 0..17 {
        for j in 0..16 {
            for k in 0..256 {
                tables[i][j][k] = u32::from_le_bytes([
                    data[offset],
                    data[offset + 1],
                    data[offset + 2],
                    data[offset + 3],
                ]);
                offset += 4;
            }
        }
    }
    let arr: [[[u32; 256]; 16]; 17] = tables
        .try_into()
        .map_err(|_| anyhow::anyhow!("Failed to convert ng tables to fixed array"))?;
    Ok(Box::new(arr))
}

fn write_ng_tables(tables: &[[[u32; 256]; 16]; 17]) -> Vec<u8> {
    let mut out = Vec::with_capacity(17 * 16 * 1024);
    for i in 0..17 {
        for j in 0..16 {
            for k in 0..256 {
                out.extend_from_slice(&tables[i][j][k].to_le_bytes());
            }
        }
    }
    out
}

fn search_hash(data: &[u8], expected_sha1: &[u8; 20], length: usize) -> Option<Vec<u8>> {
    if data.len() < length {
        return None;
    }
    for i in 0..=(data.len() - length) {
        let candidate = &data[i..i + length];
        let mut hasher = Sha1::new();
        hasher.update(candidate);
        let hash: [u8; 20] = hasher.finalize().into();
        if &hash == expected_sha1 {
            return Some(candidate.to_vec());
        }
    }
    None
}

/// Strip the mask, AES-decrypt and inflate the magic data, yielding the NG
/// keys followed by the decrypt tables.
fn unwrap_magic(magic: &[u8], aes_key: &[u8; 32]) -> Result<Vec<u8>> {
    let len = magic.len();

    // The mask is four consecutive fills of one seeded stream, so a single
    // draw of 4x the length gives the same bytes in the same order.
    let mut mask = vec![0u8; len * 4];
    DotNetRandom::new(jenkins_hash_bytes(aes_key) as i32).next_bytes(&mut mask);

    let mut data = magic.to_vec();
    for (i, byte) in data.iter_mut().enumerate() {
        for pass in 0..4 {
            *byte = byte.wrapping_sub(mask[pass * len + i]);
        }
    }

    let mut out = Vec::new();
    DeflateDecoder::new(&decrypt_aes(&data, aes_key)[..])
        .read_to_end(&mut out)
        .context("failed to inflate magic data — AES key does not match it")?;

    let expected = NG_KEY_BYTES + NG_TABLE_BYTES;
    if out.len() < expected {
        bail!("magic data too small: {} bytes (expected at least {})", out.len(), expected);
    }
    out.truncate(expected);
    Ok(out)
}

/// Jenkins one-at-a-time over raw bytes. Unlike the name hash, nothing is
/// lowercased first, which matters for key material.
fn jenkins_hash_bytes(data: &[u8]) -> u32 {
    let mut h: u32 = 0;
    for &b in data {
        h = h.wrapping_add(b as u32);
        h = h.wrapping_add(h << 10);
        h ^= h >> 6;
    }
    h = h.wrapping_add(h << 3);
    h ^= h >> 11;
    h.wrapping_add(h << 15)
}

/// .NET's seeded `System.Random` (Knuth subtractive). The mask bytes are only
/// reproducible by matching this generator exactly, including its overflow.
struct DotNetRandom {
    seed_array: [i32; 56],
    inext: usize,
    inextp: usize,
}

impl DotNetRandom {
    const MBIG: i32 = i32::MAX;
    const MSEED: i32 = 161_803_398;

    fn new(seed: i32) -> Self {
        let subtraction = if seed == i32::MIN { i32::MAX } else { seed.abs() };
        let mut seed_array = [0i32; 56];

        let mut mj = Self::MSEED.wrapping_sub(subtraction);
        seed_array[55] = mj;
        let mut mk: i32 = 1;

        for i in 1..55 {
            let ii = (21 * i) % 55;
            seed_array[ii] = mk;
            mk = mj.wrapping_sub(mk);
            if mk < 0 {
                mk = mk.wrapping_add(Self::MBIG);
            }
            mj = seed_array[ii];
        }

        for _ in 1..5 {
            for i in 1..56 {
                seed_array[i] = seed_array[i].wrapping_sub(seed_array[1 + (i + 30) % 55]);
                if seed_array[i] < 0 {
                    seed_array[i] = seed_array[i].wrapping_add(Self::MBIG);
                }
            }
        }

        Self { seed_array, inext: 0, inextp: 21 }
    }

    fn internal_sample(&mut self) -> i32 {
        let mut inext = self.inext + 1;
        if inext >= 56 {
            inext = 1;
        }
        let mut inextp = self.inextp + 1;
        if inextp >= 56 {
            inextp = 1;
        }

        let mut ret = self.seed_array[inext].wrapping_sub(self.seed_array[inextp]);
        if ret == Self::MBIG {
            ret -= 1;
        }
        if ret < 0 {
            ret = ret.wrapping_add(Self::MBIG);
        }

        self.seed_array[inext] = ret;
        self.inext = inext;
        self.inextp = inextp;
        ret
    }

    fn next_bytes(&mut self, buffer: &mut [u8]) {
        for byte in buffer.iter_mut() {
            *byte = (self.internal_sample() % 256) as u8;
        }
    }
}

static PC_AES_KEY_HASH: [u8; 20] = [
    0xA0, 0x79, 0x61, 0x28, 0xA7, 0x75, 0x72, 0x0A, 0xC2, 0x04,
    0xD9, 0x81, 0x9F, 0x68, 0xC1, 0x72, 0xE3, 0x95, 0x2C, 0x6D,
];
